### ISSUE TITLE
Dependabot alert

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-docs#122]
Triage and resolve if necessary

https://github.com/open-dollar/od-docs/security/dependabot/52

**Comment by jahabeebs** [comment]
@pi0neerpat We don't need to address this now because we aren't using any user-provided URLs that need sanitization:

<img width="370" alt="Screenshot 2024-07-24 at 5 53 28 PM" src="https://github.com/user-attachments/assets/f60541bf-8b83-41de-ab1d-d0c0602ddcc0">

<img width="319" alt="Screenshot 2024-07-24 at 5 53 12 PM" src="https://github.com/user-attachments/assets/e954b213-89c7-47a9-b4cc-381dfafab8a3">

I opened an issue about this in the Tina CMS repo because it's dependent on a package that needs updating:

https://github.com/tinacms/tinacms/issues/4682

**Comment by pi0neerpat** [comment]
Amazing thank you!
